steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vernal-guide-448217-j7/your-app', '-f', 'Backend/HackathonProject/test.txt', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'your-app',
           '--image', 'gcr.io/vernal-guide-448217-j7/your-app',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '900s'
