steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-app', 'backend/hackathonproject']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'your-app',
           '--image', 'gcr.io/$PROJECT_ID/your-app',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

timeout: '900s'
